# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de7da918e8ff7c63a48abe22bd06dffcad575ad037a3afb7bb268fa0bee702992214849fdf95dc77a24d4e206ed51e1031f810acc6803e8b09d51da843993ee9

test:
  secret_key_base: 7051894ddafbbc1d57e910b34c68fbd54dab7fd7b3fdd77205dad833b5aee02596fb9df1c620eb6859c0ea2811bddf59ff51444578648b5f570b60a5c34acf7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
